version: 0.2

env:
  variables:
    ci: true

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - yarn install --pure-lockfile
  build:
    commands:
      - yarn build
      - yarn test
      - yarn lint
artifacts:
  files:
    - '**/*'
  base-directory: build
