version: 0.1
phases:
  install:
    runtime-versions:
      node: 10
  pre_build:
    commands:
      - yarn install --pure-lockfile
  build:
    commands:
      - yarn build
      - yarn test --ci
artifacts:
  files:
    - '**/*'
  base-directory: build